apps/blog/urls.py
from django.urls import path
from . import views
from .views.post_views import *

app_name = 'blog'  # Вказуємо namespace для додатку

urlpatterns = [
    # path('', views.home, name='home'),  # Головна сторінка нашого сайту
    path('posts/', PostsListView.as_view(), name='blog_posts'),
    path('avatar/', AvatarUploadView.as_view(), name="upload_avatar"),
    path('posts/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('posts/create/', PostCreateView.as_view(), name='post-create'),
    path('posts/<int:pk>/edit/', PostUpdateView.as_view(), name='post-update'),
    path('posts/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

apps/shop/urls.py
# apps/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),  # головна сторінка
    path('<int:category_id>/', views.category_detail, name='category_detail'),
    path('<int:category_id>/<slug:model>/', views.product_detail, name='product_detail')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from apps.blog.views import post_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', post_views.index, name='index'),  # Головна сторінка нашого сайту
    # path('', include('apps.blog.urls', namespace='blog')),  # підключаємо з namespace
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('shop/', include('apps.shop.urls', namespace='shop')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
]
if settings.DEBUG:  # Тільки для режиму розробки
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
<!-- Основний контент -->
<main class="container my-5">
    {% block content %}{% endblock %}
</main>

<!-- Футер -->
<footer class="bg-dark text-light text-center py-3 mt-auto">
    <p>&copy; 2026 Django Blog Сергія Цеміка</p>
</footer>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

templates/partials/header.html
<meta charset="UTF-8">
<title>{% block title %}Django Blog{% endblock %}</title>

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

<!-- Навбар -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">🌐 Django Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Головна</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'blog:blog_posts' %}">Блог</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'shop:home' %}">Магазин</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">Про нас</a></li>
            </ul>
        </div>
    </div>
</nav>